name: Deploy Nuxt 3 App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
  
    - name: Build Nuxt app
      run: npm run build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nuxt3-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/nuxt3-app:latest

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker stop nuxt3-app || true
          docker rm nuxt3-app || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/nuxt3-app:latest
          docker run -d --name nuxt3-app --env-file /home/thy/appConfig/.env -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/nuxt3-app:latest
